name: alabama_beer_trail
description: Alabama Beer Trail. See nearby craft beer destinations and find nearby events.
author: Dan Roberts <droberts@alabamabrewers.org>
publish_to: none

version: 2.0.0+20

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^8.2.0
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  firebase_messaging: ^10.0.4
  flutter_widget_from_html_core: ^0.5.0+3
  font_awesome_flutter: ^8.8.1  
  http: ^0.13.3
  image: ^3.0.2
  trail_auth:
    git: 
      url: https://github.com/danroberts728/beer_trail_packages.git
      path: packages/trail_auth
  trail_location_service:
    git:
      url: https://github.com/danroberts728/beer_trail_packages.git
      path: packages/trail_location_service
  trail_database:
    git:
      url: https://github.com/danroberts728/beer_trail_packages.git
      path: packages/trail_database
  trailtab_events:
    git:
      url: https://github.com/danroberts728/beer_trail_packages.git
      path: packages/trailtab_events
  trailtab_wordpress_news:
    git:
      url: https://github.com/danroberts728/beer_trail_packages.git
      path: packages/trailtab_wordpress_news
  trailtab_places:
    git:
      url: https://github.com/danroberts728/beer_trail_packages.git
      path: packages/trailtab_places
  trailtab_badges:
    git:
      url: https://github.com/danroberts728/beer_trail_packages.git
      path: packages/trailtab_badges
  trail_profile:
    git:
      url: https://github.com/danroberts728/beer_trail_packages.git
      path: packages/trail_profile
  url_launcher: ^6.0.9

dev_dependencies:
  test: any
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/defaultprofilephoto.png
    - assets/images/fth_black.png
    - assets/images/fthglasses.jpg
    - assets/images/guild_logo_square_color.png
    - assets/images/signin_bkg.jpg
    - assets/images/stamp_outline.png