name: alabama_beer_trail
description: The Alabama Beer Trail. See nearby craft beer destinations and find nearby events.
author: Dan Roberts <droberts@alabamabrewers.org>

version: 1.0.6+7

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  carousel_slider: ^1.3.0
  webfeed: ^0.4.2
  http: ^0.12.0
  intl: ^0.15.8
  firebase_core: ^0.4.0+8
  cloud_firestore: ^0.12.7+1
  location: ^2.3.5
  cached_network_image: ^2.0.0-rc
  url_launcher: ^5.1.2
  firebase_auth: ^0.14.0
  google_sign_in: ^4.0.6
  flutter_auth_buttons: ^0.5.0
  image_picker: ^0.6.1+4
  permission_handler: ^3.2.2
  firebase_storage: ^3.0.6
  image: ^2.1.5
  image_cropper: ^1.1.0
  font_awesome_flutter: ^8.5.0
  firebase_analytics: ^5.0.9
  google_maps_flutter: ^0.5.21
  clustering_google_maps: ^0.1.2
  firebase_crashlytics: ^0.1.2
  flutter_html: ^0.11.1
  html_unescape: ^1.0.1

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/signin_bkg.jpg
    - assets/images/fthglasses.jpg
    - assets/images/defaultprofilephoto.png
    - assets/images/fth_black.png
    - assets/images/newsfeed_empty_image.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
