name: alabama_beer_trail
description: The Alabama Beer Trail. See nearby craft beer destinations and find nearby events.
author: Dan Roberts <droberts@alabamabrewers.org>

version: 1.1.1+13

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.2.1
  cloud_firestore: ^0.14.0+2
  firebase_analytics: ^6.0.0
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.1.4+1
  firebase_messaging: ^7.0.0
  firebase_performance: ^0.4.0
  firebase_storage: ^4.0.0
  flutter_auth_buttons: ^0.8.0
  flutter_widget_from_html_core: ^0.4.2
  font_awesome_flutter: ^8.8.1  
  google_maps_cluster_manager: ^0.1.0
  google_maps_flutter: ^0.5.28+1
  google_sign_in: ^4.5.1
  html_unescape: ^1.0.1+3
  http: ^0.12.1
  image: ^2.1.13
  image_cropper: ^1.2.3
  image_picker: ^0.6.7+4
  intl: ^0.16.1
  location: ^3.0.2
  permission_handler: ^3.2.2
  url_launcher: ^5.4.11
  webfeed: ^0.4.2

dev_dependencies:
  test: any
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/signin_bkg.jpg
    - assets/images/fthglasses.jpg
    - assets/images/defaultprofilephoto.png
    - assets/images/fth_black.png
    - assets/images/newsfeed_empty_image.jpg
    - assets/images/guild_logo_square.png
    - assets/images/guild_logo_state.png
    - assets/images/guild_logo_state_color.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
