name: alabama_beer_trail
description: The Alabama Beer Trail. See nearby craft beer destinations and find nearby events.
author: Dan Roberts <droberts@alabamabrewers.org>

version: 1.0.7+8

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^2.2.1
  webfeed: ^0.4.2
  http: ^0.12.1
  intl: ^0.15.8
  firebase_core: ^0.4.5
  cloud_firestore: ^0.13.7
  location: ^3.0.2
  cached_network_image: ^2.2.0+1
  url_launcher: ^5.4.11
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  flutter_auth_buttons: ^0.8.0
  image_picker: ^0.6.7+3
  permission_handler: ^3.2.2
  firebase_storage: ^3.1.6
  image: ^2.1.13
  image_cropper: ^1.2.3
  font_awesome_flutter: ^8.8.1
  firebase_analytics: ^5.0.16
  google_maps_flutter: ^0.5.21+3
  clustering_google_maps: ^0.1.2
  firebase_crashlytics: ^0.1.3+3
  flutter_html: ^1.0.0
  html_unescape: ^1.0.1+3

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/signin_bkg.jpg
    - assets/images/fthglasses.jpg
    - assets/images/defaultprofilephoto.png
    - assets/images/fth_black.png
    - assets/images/newsfeed_empty_image.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
