name: iOS Build

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'
    - name: Decode GoogleService-Info.plist
      env:
        FIREBASE_SECRET: ${{ secrets.GOOGLE_SERVICES_PLIST }}
      run: echo $FIREBASE_SECRET > ./ios/Runner/GoogleService-Info.plist
      working-directory: ./temp
    - run: flutter pub get
      working-directory: ./temp
    - run: flutter build ios --release --no-codesign
      working-directory: ./temp
